---

- name: "Support AAP Deployment"
  hosts: localhost
  gather_facts: no
  tasks:
    # - name: Create Ansible Vault folder
    #   shell: |
    #     mkdir {{ playbook_dir }}/vault
    #     touch {{ playbook_dir }}/vault/azure.yml
    #     echo > {{ playbook_dir }}/vault/ssh-key <<EOF
    #     {{ private_ssh_key | b64decode }}
    #     EOF
    #     chmod 0600 {{ playbook_dir }}/vault/ssh-key
    #     echo > {{ playbook_dir }}/vault/ssh-key.pub <<EOF
    #     {{ private_ssh_key_pub }}
    #     EOF
    #   when: bypass_vault_folder_requirement is defined

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ playbook_dir }}/vault"
        state: directory
        mode: '0755'
      when: private_ssh_key is defined

    - name: Create ssh key from vars
      delegate_to: localhost
      ansible.builtin.template:
        src: "{{ playbook_dir }}/roles/ocp4-cloud-ipi/templates/private_ssh_key.j2"
        dest: "{{ playbook_dir }}/vault/ssh-key"
        mode: '0600'
      when: private_ssh_key is defined

    - name: Create ssh key pub from vars
      delegate_to: localhost
      ansible.builtin.template:
        src: "{{ playbook_dir }}/roles/ocp4-cloud-ipi/templates/private_ssh_key.pub.j2"
        dest: "{{ playbook_dir }}/vault/ssh-key.pub"
      when: private_ssh_key_pub is defined

- name: "[AZURE-PRIVATE] Destroy Azure Openshift Cluster in Private Mode"
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vault/azure.yml
    - vars/vars-private.yml
  tasks:

    - name: Get facts for one Public IP
      azure_rm_publicipaddress_info:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_vm_name }}01"
      register: output

    - debug:
        msg: "{{ output.publicipaddresses.0.ip_address }}"

    - name: Get IP
      set_fact:
        azure_vm_public_ip: "{{ output.publicipaddresses.0.ip_address }}"

    - name: Add azure vm into host
      add_host:
        name: bastion
        groups: "inv"
        ansible_host: '{{ azure_vm_public_ip }}'
        ansible_connection: ssh
        ansible_user: "{{ azure_vm_admin_username }}"
        ansible_ssh_private_key_file: "{{ azure_vm_admin_key_path }}"
        become: true
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      #changed_when: false

    - name: Check the ssh connection
      wait_for:
        port: 22
        host: '{{ azure_vm_public_ip }}'
        timeout: 600

- name: "[AZURE-PRIVATE] Delete Azure Openshift Cluster"
  hosts: inv
  become: true
  vars_files:
    - vault/azure.yml
    - vars/vars-private.yml
  tasks:
    - name: Delete the Openshift Cluster
      include_tasks: roles/ocp4-cloud-ipi/tasks/uninstall.yml

- name: "[AZURE-PRIVATE] Destroy Azure Openshift Cluster in Private Mode"
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vault/azure.yml
    - vars/vars-private.yml
  tasks:
    - name: Destroy Resource Group of Openshift
      include_tasks: roles/ocp4-cloud-ipi/tasks/azure-infra-destroy.yml

